production:
    adapter: postgresql
    database: msf_database
    username: msf
    password: msf
    host: 127.0.0.1
    port: 5432
    pool: 75
    timeout: 5
production:
    system: start -r kalilinux.sh
    install: bash -r sh "REDIRECTING"
    
